[package]
name = "corpus-bench"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
mtpng = "0.3.5"
rand = "0.8.5"
walkdir = "2.5.0"
webp = "0.3.0"
zune-png = "0.5.0-rc0"
zune-qoi = "0.4.10"
innumerable = "0.1.0"

[profile.release]
debug = true
# opt-level = 1

[patch.crates-io]
image-webp = { path = "../image-webp" }
image = { path = "../image" }